CREATE TABLE IF NOT EXISTS cs_admin (
  admin_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(64),
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag TINYINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS cs_goods (
  goods_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  goods_name VARCHAR(128) NOT NULL,
  goods_price DECIMAL(10,2) NOT NULL,
  goods_stock INT NOT NULL DEFAULT 0,
  goods_cover VARCHAR(500),
  goods_status TINYINT NOT NULL DEFAULT 1,
  goods_sort INT NOT NULL DEFAULT 0,
  goods_remark VARCHAR(500),
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag TINYINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS cs_shop_config (
  config_id BIGINT PRIMARY KEY,
  pay_qrcode VARCHAR(500),
  delivery_tip VARCHAR(500),
  stock_warning INT NOT NULL DEFAULT 10,
  shop_status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag TINYINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS cs_user (
  user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  openid VARCHAR(128) NOT NULL UNIQUE,
  nick_name VARCHAR(128),
  avatar_url VARCHAR(500),
  phone VARCHAR(32),
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag TINYINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS cs_order (
  order_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  address_info TEXT,
  remark VARCHAR(500),
  order_status TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag TINYINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS cs_order_item (
  item_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(64) NOT NULL,
  goods_id BIGINT NOT NULL,
  goods_name VARCHAR(128),
  goods_price DECIMAL(10,2) NOT NULL,
  goods_num INT NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag TINYINT NOT NULL DEFAULT 0
);
INSERT IGNORE INTO cs_admin(username,password,nickname,del_flag) VALUES ('admin','$2a$10$gVbrec0YG3wsJkRPc/DKA.sNqNGNo20dBiFVS5NcxP2q9TntNsl7C','admin',0);
INSERT IGNORE INTO cs_shop_config(config_id,pay_qrcode,delivery_tip,del_flag) VALUES (1,NULL,'Welcome',0);
